---
- block:
  - name: import Microsoft key
    rpm_key:
      state: present
      key: "{{ microsoft_key_url }}"
  - name: enable Microsoft Repo
    get_url:
      url: "{{ microsoft_repo_url }}"
      dest: /etc/yum.repos.d/microsoft.repo
      owner: root
      group: root
      mode: "0644"
  - name: install dependencies
    dnf:
      name: "{{ powershell_core_dependencies }}"
      state: present
  - name: install PowerShell Core
    dnf:
      name: powershell
      state: present
  become: True
  become_user: root
